version: '3'
services:
  household-task-app:
    build: ./backend
    ports:
       - "8091:8091" #app port
       - "8093:5005" #port for remote debugging
    depends_on:
       - database_postgres_dev
       - mailhog
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
      - "JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=5005,server=y,suspend=n"
    restart: always
  database_postgres_dev:
    container_name: 'database_postgres_dev'
    image: postgres
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
       POSTGRES_DB: household-dev
    ports:
      - "54321:5432"
  mailhog:
    container_name: 'mailhog'
    image: mailhog/mailhog
    command: ["-storage=maildir", "-maildir-path=/maildir"]
    volumes:
      - ./volumes/mailhog/volume:/maildir
    ports:
      - "1025:1025" # smtp server
      - "8025:8025" # web ui