version: '3'
services:
  household-task-app:
    build: ./backend
    ports:
       - "8092:8091"
    depends_on:
       - database_postgres_dev
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
  database_postgres_dev:
    container_name: 'postgres_dev'
    image: postgres
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
       POSTGRES_DB: household-dev
    ports:
      - "54321:5432"